CREATE TABLE app_user (
    id UUID NOT NULL,
    username VARCHAR(50) NOT NULL,
    display_name VARCHAR(100),

    CONSTRAINT pk_app_user PRIMARY KEY (id),
    CONSTRAINT uq_app_user_username UNIQUE (username)
);

CREATE TABLE burger_of_the_day (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    text VARCHAR(150) NOT NULL,
    commentary VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    publish_date DATE NOT NULL,
    hidden BOOLEAN NOT NULL DEFAULT FALSE,
    creator_id UUID NOT NULL,

    CONSTRAINT pk_burger_of_the_day PRIMARY KEY (id),
    CONSTRAINT fk_burger_creator FOREIGN KEY (creator_id) REFERENCES app_user(id) ON DELETE RESTRICT,
    CONSTRAINT ck_burger_text_not_blank CHECK (btrim(text) <> '')
);
